//
//  MainBeerRouter.swift
//  ApiBeerCleanSwift
//
//  Created by André Brilho on 05/05/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainBeerRoutingLogic {
    func routeToDetail()
}

protocol MainBeerDataPassing {
  var dataStore: MainDataStore? { get }
}

class MainBeerRouter: NSObject, MainBeerRoutingLogic, MainBeerDataPassing{
  weak var viewController: MainBeerViewController?
  var dataStore: MainDataStore?
    
    func routeToDetail() {
        let storyBoard = UIStoryboard(name: "Main", bundle:nil)
        let detail = storyBoard.instantiateViewController(withIdentifier: "detailVC")
        var destinationDS = (detail as! BeerDetailViewController).router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        viewController?.navigationController?.pushViewController(detail, animated: true)
    }
    
    func passDataToSomewhere(source: MainDataStore, destination: inout BeerDetailDataStore) {
        destination.selectedBeer = source.selectedBeer
}
}
