//
//  MainBeerWorker.swift
//  ApiBeerCleanSwift
//
//  Created by André Brilho on 05/05/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

class MainBeerWorker{
    
    func getBers() -> Promise<[MainBeer.Beer]> {
        let url = URL(string: Constants.URL_BASE)!
        return Promise<[MainBeer.Beer]> { seal in
            URLSession.shared.dataTask(with: url) { (data, response, error) in
                if let data = data {
                    let objParse = try! JSONDecoder().decode([MainBeer.Beer].self, from: data)
                    seal.fulfill(objParse)
                } else {
                    seal.reject(NSError(domain: "", code: 0, userInfo: nil))
                }
                }.resume()
        }
    }
    
}
