//
//  MainBeerModels.swift
//  ApiBeerCleanSwift
//
//  Created by André Brilho on 05/05/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainBeer
{
        struct Beer:Decodable{
            var id: Int?
            var name: String?
            var tagline: String?
            var description: String?
            var image_url: String?
            var attenuation_level : Float?
            var abv : Float?
        }
}

