//
//  MainBeerPresenter.swift
//  ApiBeerCleanSwift
//
//  Created by André Brilho on 05/05/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBeerPresentationLogic {
    func reloadTable()
    func routeToDetail()
    func showData(listBeer:[MainBeer.Beer])
    func showError()
}

class MainBeerPresenter: MainBeerPresentationLogic{

    
    func showData(listBeer: [MainBeer.Beer]) {
        viewController?.showData(listBeer)
    }
    
  weak var viewController: MainBeerDisplayLogic?
    
    func reloadTable() {
        viewController?.reloadTable()
    }
    
    func routeToDetail() {
        viewController?.routeToDetail()
    }
    
    func showError(){
        viewController?.showError(erro: "OPS")
    }
}
