//
//  BeerDetailRouter.swift
//  ApiBeerCleanSwift
//
//  Created by André Brilho on 05/05/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BeerDetailRoutingLogic {
}

protocol BeerDetailDataPassing
{
  var dataStore: BeerDetailDataStore? { get }
}

class BeerDetailRouter: NSObject, BeerDetailRoutingLogic, BeerDetailDataPassing
{
  weak var viewController: BeerDetailViewController?
  var dataStore: BeerDetailDataStore?
  
}
