//
//  BeerDetailPresenter.swift
//  ApiBeerCleanSwift
//
//  Created by André Brilho on 05/05/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BeerDetailPresentationLogic
{
  func presentSomething(response: BeerDetail.Something.Response)
}

class BeerDetailPresenter: BeerDetailPresentationLogic
{
  weak var viewController: BeerDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: BeerDetail.Something.Response)
  {
    let viewModel = BeerDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
