//
//  BeerDetailInteractor.swift
//  ApiBeerCleanSwift
//
//  Created by André Brilho on 05/05/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BeerDetailBusinessLogic {
    func load()
    }

protocol BeerDetailDataStore {
    var selectedBeer:MainBeer.Beer? { get set }
}

class BeerDetailInteractor: BeerDetailBusinessLogic, BeerDetailDataStore {
    
  var presenter: BeerDetailPresentationLogic?
  var worker: BeerDetailWorker?
    var selectedBeer: MainBeer.Beer?
    
    init(worker:BeerDetailWorker = BeerDetailWorker()) {
        self.worker = worker
    }

  
  func load(){
    presenter?.showDesc(desc: selectedBeer?.description ?? "")
    presenter?.showName(name: selectedBeer?.name ?? "")
    presenter?.showImage(imgUrl: selectedBeer?.image_url ?? "")
  }
}
