//
//  BeerDetailViewController.swift
//  ApiBeerCleanSwift
//
//  Created by André Brilho on 05/05/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AlamofireImage

protocol BeerDetailDisplayLogic: class {
    func showName(name: String)
    func showDesc(desc: String)
     func showImage(imgUrl: String)
}

class BeerDetailViewController: UIViewController, BeerDetailDisplayLogic
{
    
    @IBOutlet weak var img: UIImageView!
    @IBOutlet weak var lbl: UILabel!
    @IBOutlet weak var txtView: UITextView!
    
    
  var interactor: BeerDetailBusinessLogic?
  var router: (NSObjectProtocol & BeerDetailRoutingLogic & BeerDetailDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  private func setup() {
    let viewController = self
    let interactor = BeerDetailInteractor()
    let presenter = BeerDetailPresenter()
    let router = BeerDetailRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }

    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.load()
    }
    
    func showName(name: String) {
        lbl.text = name
    }
    
    func showDesc(desc: String) {
        txtView.text = desc
    }
    
    func showImage(imgUrl: String){
        img.af_setImage(withURL: URL(string: imgUrl)!)
    }
        
}
